name: build-exe
on:
  push:
    branches:
      - 'main'
    # paths:
    #   - '**.py'

jobs:
  build-executable:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.8' 
      - run: dir
      - name: Install requirements
        run: py -m pip install -r requirements.txt
      - name: Install pyinstaller
        run: py -m pip install pyinstaller pywin32-ctypes
      - run: dir
      - name: Build exe
        run: pyinstaller --console --onefile bloodweb-clicker.py
      - uses: actions/upload-artifact@v3
        with:
          name: bloodweb-clicker
          path: ./dist/bloodweb-clicker.exe
